window.PORTFOLIO_DATA = {
  featured: [
    {
      id: "college-ext",
      index: "01",
      title: "Beyond Syllabus",
      label: "College Ext · Learning platform",
      summary: "An interactive course platform that turns dense engineering subjects into structured notes, visual modules, practice modes, podcasts, and guided study tools.",
      detail: "The repository uses a Next.js monorepo with shared authentication, validation, database, AI, and interface packages. Original course modules are integrity-checked, built independently, and embedded into a consistent learning flow instead of being reduced to static notes.",
      flow: ["Student chooses a subject and unit", "The platform loads verified course content or an isolated interactive module", "Practice, case study, podcast, and test modes reuse the same curriculum", "Progressive tools help the student move from reading to application"],
      tags: ["Next.js", "TypeScript", "MySQL", "Prisma", "PWA"],
      source: "https://github.com/Mohith2912/College-Ext",
      live: "https://beyond-syllabus-learn.vercel.app",
      tone: "crimson"
    },
    {
      id: "voe",
      index: "02",
      title: "VOE Web",
      label: "Voice of Easwarians · Community platform",
      summary: "The official digital home of Voice of Easwarians, connecting students through technology, creativity, events, collaboration, and campus initiatives.",
      detail: "The React and Vite experience opens with a cinematic VOE emblem reveal, then presents the community through focused Home, About, Gallery, Team, Events, and Contact views. Accessible controls, reduced-motion handling, responsive layouts, expandable team groups, and a mail-ready contact flow keep the experience expressive and usable.",
      flow: ["A cinematic emblem introduction establishes the VOE identity", "Visitors discover the community's vision, mission, values, and activities", "Dedicated views introduce events, media, leadership, and functional teams", "The contact experience helps students participate, collaborate, or share an idea"],
      tags: ["React", "Vite", "Community", "Responsive UI"],
      source: "https://github.com/Mohith2912/VOE_WEB",
      live: "https://voe-web-gilt.vercel.app",
      tone: "amber"
    },
    {
      id: "urban-furniture",
      index: "03",
      title: "Urban Furniture OS",
      label: "Business operations · Full stack",
      summary: "A connected operating system for a furniture business: inventory, purchasing, sales, GST invoices, payments, expenses, budgets, accounting, and reporting.",
      detail: "The Next.js workspace sends role-aware requests to a Flask accounting API backed by PostgreSQL. Server rules calculate tax and ledger entries, posted documents become immutable, and authenticated server-sent events refresh open workspaces when the database revision changes.",
      flow: ["Staff create contacts, products, and commercial documents", "The API validates permissions, stock, tax, and accounting rules", "PostgreSQL stores auditable documents and double-entry records", "Dashboards, statements, alerts, and reports convert records into action"],
      tags: ["Next.js", "Flask", "PostgreSQL", "GST", "SSE"],
      source: "https://github.com/Mohith2912/UrbanFurniture",
      live: "https://urban-furniture-web.vercel.app",
      tone: "blue"
    },
    {
      id: "peoplepay360",
      index: "04",
      title: "PeoplePay360",
      label: "HR & payroll · Enterprise workflow",
      summary: "An integrated HR and payroll platform connecting employee records, schedules, attendance, leave, salary rules, payruns, payslips, reporting, PDF generation, and email delivery.",
      detail: "The React/Next.js frontend calls a role-protected backend through a same-origin rewrite. Domain handlers validate each action, Prisma transactions preserve payroll state in MySQL, and the payroll engine combines contracts, schedules, attendance, leave, and sequenced salary rules into validated payslips.",
      flow: ["HR defines people, contracts, schedules, and salary structures", "Attendance and approved leave establish period inputs", "The payroll engine computes rule-based earnings and deductions", "Authorized users validate, pay, export, and email auditable payslips"],
      tags: ["Next.js", "Prisma", "MySQL", "RBAC", "Payroll"],
      source: "https://github.com/Mohith2912/PeoplePay360",
      live: "https://people-pay360-mu.vercel.app",
      tone: "violet"
    },
    {
      id: "extendquality",
      index: "05",
      title: "EXtendQuality",
      label: "Industrial AI · Computer vision",
      summary: "A confidence-aware quality inspection concept for manufacturing that combines deterministic computer vision with selective multimodal reasoning.",
      detail: "Industrial camera frames are enhanced with OpenCV and inspected by YOLOv11. A quality intelligence layer accepts confident detections automatically and routes ambiguous cases to a vision-language model, then records recommendations, history, and quality KPIs.",
      flow: ["Industrial camera captures a product image", "OpenCV improves the frame and YOLO localises possible defects", "Confidence rules separate automatic decisions from uncertain cases", "VLM reasoning, recommendations, history, and KPIs support the quality team"],
      tags: ["OpenCV", "YOLOv11", "VLM", "Next.js", "Drizzle"],
      source: "https://github.com/Mohith2912/Extend-Quality",
      live: null,
      tone: "green"
    },
    {
      id: "unihealth",
      index: "06",
      title: "UniHealth",
      label: "Healthcare operations · Secure workflows",
      summary: "A hospital operations workspace for doctors, beds, wards, patient queues, analytics, recovery, and server-generated audit history.",
      detail: "An accessible multi-page interface talks to an authenticated Node.js API and MySQL database. Every query is scoped to one hospital, transactions and version checks protect concurrent changes, and domain rules prevent conflicting consultations or unsafe record deletion.",
      flow: ["An administrator creates a private hospital workspace", "Doctors, wards, beds, and patient tokens become structured records", "Validated queue transitions coordinate consultation flow", "Dashboards, analytics, CSV exports, and audit history expose operational state"],
      tags: ["Node.js", "MySQL", "Security", "Analytics", "Testing"],
      source: "https://github.com/Mohith2912/Unihealth-Hospital-Management",
      live: null,
      tone: "cyan"
    },
    {
      id: "fairdispatch",
      index: "07",
      title: "FairDispatch",
      label: "Logistics · Workload intelligence",
      summary: "A delivery-dispatch prototype exploring fairer workload assignment, live fleet visibility, stop progress, ETA estimates, disputes, and support workflows.",
      detail: "The default Express API stores prototype data in local JSON files. Load assignment ranks drivers using fairness and workload signals; route endpoints track stop progress, while a separate Python experiment trains a random-forest rotation model for future decision support.",
      flow: ["A manager creates a delivery load", "The service scores available driver records by fairness and workload", "The selected assignment updates workload and route state", "Fleet, dispute, ETA, and support views surface exceptions for human review"],
      tags: ["Express", "JavaScript", "Firebase", "Random Forest", "Logistics"],
      source: "https://github.com/Mohith2912/Fair-Dispatch",
      live: null,
      tone: "orange"
    }
  ],
  repositories: [
    { name: "Mohith-Dharshan.J.CSE-EEC", category: "portfolio", language: "HTML", description: "This portfolio: a fast, accessible project narrative and searchable map of Mohith’s public engineering work." },
    { name: "College-Ext", category: "learning", language: "TypeScript", description: "Beyond Syllabus combines verified engineering course modules, notes, practice, case studies, podcasts, authentication, and AI-assisted study." },
    { name: "UrbanFurniture", category: "product", language: "Python", description: "A furniture business OS connecting stock, trade documents, GST, double-entry accounting, approvals, and reports." },
    { name: "PeoplePay360", category: "product", language: "JavaScript", description: "A role-aware HR and payroll system that converts workforce records into validated, auditable payslips." },
    { name: "Unihealth-Hospital-Management", category: "healthcare", language: "JavaScript", description: "A secure hospital workspace for doctors, capacity, patient queues, analytics, recovery, and audit history." },
    { name: "VOE-WEB", category: "design", language: "JavaScript", description: "The current cinematic website for Voice of Easwarians, built as a responsive editorial experience." },
    { name: "VOE_WEB", category: "design", language: "CSS", description: "The deployed Voice of Easwarians community website, with a cinematic introduction and dedicated mission, activities, team, events, and contact views." },
    { name: "Voice-Of-Easwarians", category: "design", language: "CSS", description: "A static event presence for the VOE community and its Miracle 2026 hackathon." },
    { name: "voe", category: "design", language: "Python", description: "A parallel Miracle 2026 event site experiment with pages and brand assets for the VOE community." },
    { name: "Extend-Quality", category: "ai", language: "TypeScript", description: "An explainable inspection architecture combining OpenCV, YOLO, confidence routing, VLM review, and KPI history." },
    { name: "ExtQlt", category: "ai", language: "JavaScript", description: "A React/Vite interface exploration for the EXtendQuality industrial inspection concept." },
    { name: "Fair-Dispatch", category: "ai", language: "JavaScript", description: "A logistics prototype for workload-aware assignment, fleet operations, ETA, disputes, and support." },
    { name: "UXVision-AI", category: "ai", language: "JavaScript", description: "An AI UX auditor exploring URL, screenshot, and code analysis with Lighthouse, vision models, and redesign generation." },
    { name: "Eye-Drowsy-Detector", category: "ai", language: "Python", description: "A webcam safety tool using MediaPipe landmarks and Eye Aspect Ratio to detect prolonged eye closure and trigger an alarm." },
    { name: "Drowsy-detector", category: "ai", language: "Python", description: "A compact version of the real-time drowsiness detection pipeline with modular eye and alarm helpers." },
    { name: "express-openai-agent", category: "ai", language: "JavaScript", description: "A production-shaped Express REST wrapper around a small AI agent with configuration and a browser client." },
    { name: "EcoSphere-Web", category: "product", language: "JavaScript", description: "A separated frontend, backend, and database web application exploring sustainability-focused product workflows." },
    { name: "AssetFlow", category: "product", language: "JavaScript", description: "A layered asset-management application with models, controllers, routes, middleware, and a Vite client." },
    { name: "Workforce-Management-System", category: "product", language: "TypeScript", description: "A React, Express, Prisma, PostgreSQL, and Redis platform for leave, attendance, and payroll inputs." },
    { name: "Bussiness-type-demo-website", category: "design", language: "TypeScript", description: "A Next.js business website prototype created to explore a polished commercial interface." },
    { name: "Calender-assignment", category: "utility", language: "JavaScript", description: "A Vite calendar application focused on date-based planning and interaction." },
    { name: "Student-Grade-Tracker", category: "learning", language: "CSS", description: "A Java and SQLite grade-management system with student records, performance statistics, and a responsive dashboard." },
    { name: "Student-Expense-Tracker", category: "utility", language: "HTML", description: "Spendora separates transactions, budgets, goals, and analytics into a clear student finance workflow." },
    { name: "Leetcode-Activity-Tracker", category: "learning", language: "CSS", description: "A small dashboard and service for visualising coding-practice activity." },
    { name: "Leetcode", category: "code", language: "Java", description: "A growing Java solution archive covering core interview problems such as Two Sum and Roman to Integer." },
    { name: "CCC", category: "code", language: "C++", description: "Thirty-two beginner C++ exercises with corrected solutions, explanations, approach notes, and complexity." },
    { name: "QR-Scanner", category: "utility", language: "JavaScript", description: "A lightweight browser QR-scanning utility with a focused camera-to-result interaction." },
    { name: "Unihealth-Pharmacy-Management", category: "healthcare", language: "HTML", description: "A pharmacy operations interface covering inventory, reservations, alerts, analytics, and authentication." },
    { name: "Unihealth-User-App", category: "healthcare", language: "JavaScript", description: "A mobile-oriented healthcare client with booking, checkout, family, emergency, doctor, and hospital flows." },
    { name: "LogicBreak-Img", category: "design", language: "Assets", description: "A visual identity archive containing final LogicBreak event marks and clean text-only exports." },
    { name: "Mohith2912", category: "portfolio", language: "Markdown", description: "Mohith’s GitHub profile README: current focus, technology map, featured work, and activity overview." }
  ]
};
